### ISSUE TITLE
Voting Procedure Docs

### ISSUE THREAD

**Issue by damacus** [sous-chefs/website#12]
Document on the website: 
- Voting Procedure
- ChefConf as the primary location with invites into Slack those that can't make it.
- publicising it in the mailing list.

**Comment by damacus** [comment]
Condorcet voting

**Comment by josephholsten** [comment]
Needs to specify:
- when nominations begin
- when noms end (I suggest closing circle at chefconf summit)
- when voting begins (also closing circle)
- when it ends (before the final closing ceremony at chefconf)
- how it is announced (can we get it announced during closing ceremony at chefconf?)

**Comment by damacus** [comment]
As inclusive as this feels, it leaves out all the people who can't attend the Conf

**Comment by josephholsten** [comment]
I'm just talking about the timing here, I want the actual participation to occur on the slack channel. Does that seem reasonable?

**Comment by damacus** [comment]
I'm closing this one down now, as I don't feel like we're going to actually do anything with it.
