### ISSUE TITLE
broken link on tranferring to sous chefs page

### ISSUE THREAD

**Issue by jlosito** [sous-chefs/website#87]
## :ghost: Brief Description

There's a broken link on the "Tranferring to Sous Chefs" page on becoming a member.

## :tophat: Platform details

Firefox 70.0.1

## Steps To Reproduce

1. Go to the current transferring page on the website. https://sous-chefs.org/docs/transferring/
2. Scroll down to "Joining Sous-Chefs" section
3. Click on the "becoming a member" link

## :police_car: Expected behavior

Link one to the "Becoming a member" page possibly linked below.

https://sous-chefs.org/docs/becoming-a-member/

**Comment by JohnRoesler** [comment]
Fixed!

**Comment by JohnRoesler** [comment]
Thank you for reporting the bug 👍
